collections:
  board_members:
    order:
      - hannes.md
      - tobigrob.md
      - leo.md
      - adrian.md
      - janschu.md
      - francisco.md
      - jana.md
      - arthur.md
      - chris.md